name: Life spectator
title: spectator | A blog informs you of my interests
description: spectator is A blog informs you of my interests and A templete for Jekyll inspired by Netflix
tags:
  - blog
  - cook
  - Brot
  - Schokolade
  - sport
  - skill
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: mz.hisia@gmail.com
disqus_username: https-dromide-github-io
